import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { Toaster } from "sonner";
import Script from "next/script";
import Providers from "./providers";
import { AuthContextProvider } from "./context/authContext";



config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
    <AuthContextProvider>

      <Providers>
      <body className="min-h-full flex flex-col">

        <div className="flex min-h-screen flex-col">
          {/* Navbar */}
          <Navbar />

          {/* Page Content */}
          <main className="flex-1">
            {children}

            <Script
              src="https://accounts.google.com/gsi/client"
              strategy="afterInteractive"
            />
          </main>

          <Toaster
            position="top-center"
            richColors
            closeButton
            expand
          />

          {/* Footer */}
          <Footer />
        </div>

        {/* {children} */}
      </body>
      </Providers>
      
    </AuthContextProvider>

    </html>
  );
}
