import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className="mx-auto w-full max-w-screen-xl py-10">
        
        {/* BREADCRUMB */}
        <div className="flex items-center gap-2 text-sm text-gray-500 mb-10">
            <Link href="/" className="hover:text-black transition">
                Home
            </Link>

            <span>/</span>

            <span className="text-black font-medium">
                My Account
            </span>
        </div>

        <div className="flex min-h-screen">

          {/* Sidebar */}
          <aside className="w-1/3 border-r border-gray-200 p-6">
            <div className="sticky top-6">
                
                <h2 className="text-[16px] font-medium mb-4 text-black">
                Manage My Account
                </h2>

                <nav className="flex flex-col gap-2 mb-6">

                <Link
                    href="/profile"
                    className="text-[16px] text-gray-500 font-medium px-4 py-1 transition duration-300 hover:text-[#DB4444]"
                >
                    My Profile
                </Link>

                <Link
                    href="/profile/address-book"
                    className="text-[16px] text-gray-500 font-medium px-4 py-1 transition duration-300 hover:text-[#DB4444]"
                >
                    Address Book
                </Link>

                <Link
                    href="/payment-options"
                    className="text-[16px] text-gray-500 font-medium px-4 py-1 transition duration-300 hover:text-[#DB4444]"
                >
                    My Payment Options
                </Link>

                </nav>

                <h2 className="text-[16px] font-medium mb-4 text-black">
                My Orders
                </h2>

                <nav className="flex flex-col gap-2 mb-6">

                <Link
                    href="/profile/address-book"
                    className="text-[16px] text-gray-500 font-medium px-4 py-1 transition duration-300 hover:text-[#DB4444]"
                >
                    My Returns
                </Link>

                <Link
                    href="/payment-options"
                    className="text-[16px] text-gray-500 font-medium px-4 py-1 transition duration-300 hover:text-[#DB4444]"
                >
                    My Cancellations
                </Link>

                </nav>

                <h2 className="text-[16px] font-medium mb-4 text-black">
                My Wishlist
                </h2>

            </div>
        </aside>

          {/* Content */}
          <main className="w-2/3">
            {children}
          </main>

        </div>

      </div>
  );
}
